apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: event-bus-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
       name: ConnectionStrings__rabbitmq
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
auth:
  secretStore: env-secretstore