@HelloWorld.OrderingService_HostAddress = https://localhost:8105
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGVpZCI6IjEiLCJuYmYiOjE3NDI4Njg1ODAsImV4cCI6MTc2NDkwMDU4MCwiaWF0IjoxNzQyODY4NTgwfQ.6Wm6S4CNtKi9lGqxam4_ZnDebnTXVxycDubbv0DLy2c

###

POST {{HelloWorld.OrderingService_HostAddress}}/api/orders
Content-Type: application/json
x-request-id: 1ddc1737-6a32-4b4f-bccd-63d0966348a3
Authorization : Bearer {{AccessToken}}

{
  "country": "USA",
  "state": "CA",
  "city": "San Francisco",
  "street": "123 Market St",
  "zipCode": "941032",
  "cardAlias": "Jack",
  "cardNumber": "4111111111111111",
  "cardHolderName": "John Doe",
  "cardSecurityNumber": "123456",
  "cardExpiration": "2025-12-31T23:59:59Z",
  "items": [
    {
      "productId": 100,
      "productName": "Smartphone",
      "quantity": 1,
      "unitPrice": 699.99,
      "pictureUrl": "https://example.com/images/phone-123.jpg"
    },
    {
      "productId": 101,
      "productName": "Tablet",
      "quantity": 2,
      "unitPrice": 499.99,
      "pictureUrl": "https://example.com/images/tablet-456.jpg"
    }
  ]
}

###

GET {{HelloWorld.OrderingService_HostAddress}}/api/orders
Content-Type: application/json
Authorization : Bearer {{AccessToken}}

###

GET {{HelloWorld.OrderingService_HostAddress}}/api/orders/1
Content-Type: application/json
Authorization : Bearer {{AccessToken}}

###


PUT {{HelloWorld.OrderingService_HostAddress}}/api/orders/ship/1
Content-Type: application/json
x-request-id: 1ddc1737-6a32-4b4f-bccd-63d0966348a1
Authorization : Bearer {{AccessToken}}
